# adapted from https://github.com/andyli/HaxeCI/blob/master/.travis.yml
language: haxe

haxe:
  - stable
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

install:
  # install haxelibs
  - haxelib install buddy
  - haxelib install glm

script:
  - haxe test.hxml

branches:
      only:
          - master
